resources:
- name: docker-base
  type: registry-image
  source:
    repository: alpine
jobs:
- name: publish-jvm-launch-utils
  plan:
  - get: docker-base
    trigger: true
    params:
      skip_download: true
  - put: docker-base
    get_params:
      skip_download: true
    params:
      image: blah
