inputs:
- name: sts4
- name: s3-manifest-yaml-vsix-snapshot
- name: s3-concourse-vsix-snapshot
- name: s3-bosh-vsix-snapshot
- name: s3-spring-boot-vsix-snapshot
platform: linux
run:
  path: sts4/concourse/tasks/publish-ovsx-releases.sh
image_resource:
  type: docker-image
  source:
    repository: kdvolder/sts4-build-env
  